[package]
name = "rust_lib_flutter_btc_wallet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
btc_wallet = {git = "https://github.com/hirokuma/rust-btc-keypath-wallet.git", version = "0.5.1"}
wallet_utils = { git = "https://github.com/hirokuma/rust-wallet-utils.git", version = "0.2.0" }

anyhow = "1.0.104"
flutter_rust_bridge = { version = "=2.13.0", features = ["log"] }
log = "0.4.34"
rusqlite = "0.31.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
