// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<(MutexBtcWallet, String)> createWallet({
  required Config config,
  required PathBuf walletPath,
}) => RustLib.instance.api.crateApiWrapperCreateWallet(
  config: config,
  walletPath: walletPath,
);

Future<MutexBtcWallet> loadWallet({
  required Config config,
  required String xprv,
  required PathBuf walletPath,
}) => RustLib.instance.api.crateApiWrapperLoadWallet(
  config: config,
  xprv: xprv,
  walletPath: walletPath,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Config>>
abstract class Config implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Mutex < BtcWallet >>>
abstract class MutexBtcWallet implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PathBuf>>
abstract class PathBuf implements RustOpaqueInterface {}
