// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_xprv`, `store_xprv`

Future<MutexBtcWallet> createWallet({
  required String network,
  required String electrumServer,
  required String passphrase,
  required String walletPath,
}) => RustLib.instance.api.crateApiWrapperCreateWallet(
  network: network,
  electrumServer: electrumServer,
  passphrase: passphrase,
  walletPath: walletPath,
);

Future<MutexBtcWallet> loadWallet({
  required String passphrase,
  required String walletPath,
}) => RustLib.instance.api.crateApiWrapperLoadWallet(
  passphrase: passphrase,
  walletPath: walletPath,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Mutex < BtcWallet >>>
abstract class MutexBtcWallet implements RustOpaqueInterface {}
